2024-05-10 13:20:20,231 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:32:40,729 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:34:56,682 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:35:18,476 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:36:06,859 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:37:06,582 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:39:04,225 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:39:35,924 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:39:58,920 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:43:25,314 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:48:38,384 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:49:14,591 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:51:32,334 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:53:36,865 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:54:42,523 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 13:58:00,752 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:00:45,910 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:01:06,684 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:02:24,834 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:02:41,673 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:03:22,892 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:04:25,196 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:05:21,846 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:08:10,529 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:08:50,217 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:09:23,315 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:10:46,836 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:11:09,807 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:12:41,363 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:13:50,390 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:14:18,801 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:14:48,224 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:15:35,110 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:16:48,124 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:16:51,397 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:18:44,512 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:19:01,333 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:19:44,923 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:20:30,886 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:21:34,062 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:22:37,579 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:23:07,452 INFO: ValueCheck startup [in /Users/rubywilner/Desktop/cits3403/GroupProject/app/__init__.py:52]
2024-05-10 14:23:08,328 ERROR: Exception on /login [GET] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/base.html", line 134, in top-level template code
    {% block content %}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/login.html", line 14, in block 'content'
    {{ form.label (class="form-label", id="username-label") }}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.forms.LoginForms object' has no attribute 'label'
2024-05-10 14:23:09,622 ERROR: Exception on /login [GET] [in /Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py:838]
Traceback (most recent call last):
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/routes.py", line 48, in login
    return render_template('login.html', title='Sign In', form=form)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/base.html", line 134, in top-level template code
    {% block content %}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/app/templates/login.html", line 14, in block 'content'
    {{ form.label (class="form-label", id="username-label") }}
  File "/Users/rubywilner/Desktop/cits3403/GroupProject/venv/lib/python3.9/site-packages/jinja2/utils.py", line 83, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'app.forms.LoginForms object' has no attribute 'label'
